Epic 2 bpmn 2.0
woped/t2p-classic pull request #41
Opened 2022-07-11 09:51 UTC by LinkKF

2022-07-13 18:55 UTC, NilsLeger requested changes

2022-07-13 18:55 UTC, NilsLeger commented on pom.xml
> -			<groupId>io.micrometer</groupId>
Wieso wurde hier einfach die Micrometer Dependency entfernt?

2022-11-21 07:39 UTC, KanBen86 commented on pom.xml
> -			<groupId>io.micrometer</groupId>
Die Dependency ist doppelt vorhanden. Siehe Zeilen 238-242

2022-11-21 07:40 UTC, KanBen86 commented on pom.xml
> +			<version>7.10.0</version>
Aber diese Dependency ist immernoch doppelt vorhanden.

2022-11-21 07:51 UTC, KanBen86 approved these changes
Im workspace quergeprüft, da die Ausgabe hier etwas unübersichtilich ist.

2022-12-29 20:46 UTC, nileger approved these changes

2022-12-29 20:47 UTC, merged